USE CATALOGO_JOAO;
GO

SELECT * FROM FILME
SELECT * FROM GENERO

--LISTAR TODOS OS FILMES, MOSTRANDO O NOME DO GENERO, 
--MESMO QUE UM FILME NAO POSSUA UM GÊNERO ATRELADO
SELECT idFilme,tituloFilme,nomeGenero FROM FILME 
LEFT JOIN GENERO
ON FILME.idGenero = GENERO.idGenero;

--LISTAR SOMENTE OS FILMES QUE POSSUEM GÊNERO,TRAZENDO TAMBÉM
--TODOS OS GÊNEROS QUE NSO REPRESENTEM UM FILME 

SELECT idFilme,tituloFilme,nomeGenero FROM FILME 
RIGHT JOIN GENERO
ON FILME.idGenero = GENERO.idGenero;

--LISTAR SOMENTE OS FILMES QUE POSSUAM UM GENERO DEFINIDO
-- GENEROS QUE NAO CORRESPONDA, A ALGUM FILME NAO DEVEM SER MOSTRADOS

SELECT idFilme,tituloFilme,nomeGenero FROM FILME 
INNER JOIN GENERO
ON FILME.idGenero = GENERO.idGenero;

--LISTAR TODOS OS FILMES E TODOS OS GENEROS 
--MESMO QUE NAO HAJA CORRESPONDECIA ENTRE ELES
SELECT idFilme,tituloFilme,nomeGenero FROM FILME 
FULL OUTER JOIN GENERO
ON FILME.idGenero = GENERO.idGenero;